# Form implementation generated from reading ui file 'gui-final.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(250, 300)
        Main.setMinimumSize(QtCore.QSize(250, 300))
        Main.setMaximumSize(QtCore.QSize(250, 300))
        self.centralwidget = QtWidgets.QWidget(parent=Main)
        self.centralwidget.setObjectName("centralwidget")
        self.name1 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.name1.setGeometry(QtCore.QRect(70, 10, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name1.setFont(font)
        self.name1.setIconSize(QtCore.QSize(16, 16))
        self.name1.setObjectName("name1")
        self.name2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.name2.setGeometry(QtCore.QRect(70, 60, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name2.setFont(font)
        self.name2.setObjectName("name2")
        self.voteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.voteButton.setGeometry(QtCore.QRect(10, 100, 113, 32))
        self.voteButton.setObjectName("voteButton")
        self.result_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(30, 150, 191, 81))
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")
        self.clearButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(130, 100, 113, 32))
        self.clearButton.setObjectName("clearButton")
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 36))
        self.menubar.setObjectName("menubar")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "GUI-VOTE"))
        self.name1.setText(_translate("Main", "John"))
        self.name2.setText(_translate("Main", "Jane"))
        self.voteButton.setText(_translate("Main", "VOTE"))
        self.clearButton.setText(_translate("Main", "CLEAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec())
